name: namer_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  device_preview: ^1.3.1
  supabase_flutter: ^2.10.3
  dot_shorthand_converter: ^0.0.4
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.7
  http: ^1.2.0
  intl: ^0.20.2
  uuid: ^4.3.3
  lottie: ^3.1.0
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png
    - assets/bot_small.png
    - assets/bot_animation/